site_name: 老罗投资
site_url: https://laoluotouzi.github.io/
site_author: 老罗
site_description: 【微信公众号：老罗投资 | 专注于股权投资 全网同名】/ 知行合一 日拱一卒 投资人生

# Repository
repo_name: laoluotouzi/laoluotouzi.github.io
repo_url: https://github.com/laoluotouzi/laoluotouzi.github.io
edit_uri: https://github.com/laoluotouzi/laoluotouzi.github.io/tree/main/docs/

# Copyright
copyright: Copyright &copy; 2023 LaoLuoTouZi

# Theme
theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
  font:
    text: Noto Sans SC
    code: Fira Code
  favicon: assets/images/favicon.png
  #logo: assets/images/logo.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline

# Plugins
plugins:
  - search

# Markdown扩展
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 老罗实盘周记:
      - weekly_record/2023/20230915.md
      - weekly_record/2023/20230909.md
  - 老罗基金估值:
      - index_fund/2023/20230914.md
      - index_fund/2023/20230911.md
