site_name: 老罗投资
site_url: https://laoluotouzi.github.io/
site_author: 老罗
site_description: 描述还没写
copyright: >
  &copy; 2023 老罗投资

theme:
  name: material
  custom_dir: overrides
  palette:
    primary: white
    accent: deep orange
  font:
    text: Noto Serif
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/code
  favicon: favicon.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    #- search.suggest
    #- search.highlight
    #- search.share
    - content.code.annotate
    - content.tabs.link

plugins:
  - search
  - awesome-pages:
  - git-revision-date-localized:
        enable_creation_date: true
        fallback_to_build_date: true
        type: iso_date
  - encryptcontent:
        hljs: false
        arithmatex: false
        mermaid2: false
        password_button: true
        remember_password: true
        default_expire_delay: 24
  - exclude:
        glob:
          - '*/exclude/*'
        regex:
          - '.*\[exclude\].*'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - tables
  - toc:
      permalink: '#'
      toc_depth: 4
      slugify: !!python/name:pymdownx.slugs.uslugify
  - sane_lists
  - smarty:
      smart_angled_quotes: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.progressbar
  - markdown_captions
  - customblocks

extra:
  analytics:
#    provider: google
#    property: G-144Q0VJMBT
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  disqus: "laoluotouzi-github-io"
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/laoluotouzi
      name: 老罗投资
  generator: false

extra_css:
  - assets/view-bigimg.css
  - assets/extra.css
extra_javascript:
  - assets/mathjax.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/view-bigimg.js
  - assets/extra.js

nav:
  - index.md
  - tags/index.md