site_name: 老罗投资
site_url: https://laoluotouzi.github.io/
site_author: 老罗
site_description: 【微信公众号：老罗投资 | 专注于股权投资 全网同名】/ 知行合一 日拱一卒 投资人生

# Repository
repo_name: laoluotouzi/laoluotouzi.github.io
repo_url: https://github.com/laoluotouzi/laoluotouzi.github.io
edit_uri: https://github.com/laoluotouzi/laoluotouzi.github.io/tree/main/docs/

# Copyright
copyright: Copyright &copy; 2023 LaoLuoTouZi

# Theme
theme:
  name: material
  #custom_dir: overrides
  language: zh
  features:
    # Navigation
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    # - navigation.instant # some features may not work properly with XHR
    - navigation.tracking # the URL changes with the active anchor
    - navigation.tabs # first top-level folders are shown as tabs
    # - navigation.tabs.sticky # tabs always show
    # - navigation.sections # second-level folders are expanded
    # - navigation.expand # all folders are expanded
    - navigation.indexes # link an index page to its parent folder
    - navigation.top # show the back-to-top button
    # - toc.integrate # show the table of contents in the navigation panel

    # Search
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search
    - search.suggest # display the likeliest completion for the last word
    - search.highlight # highlight all occurrences
    - search.share # show a share button of the current search

    # Header
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-header/
    # - header.autohide # hide the post title when scroll down

    # Content
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate # add comment to code blocks
    - content.tabs.link # link tabs with the same label
  palette:
    - scheme: default
      primary: white
  font:
    text: Noto Sans SC
    code: Fira Code
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  icon:
    logo: logo
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  extra:
    social:
      - type: 'github'
        link: 'https://github.com/laoluotouzi'

# Plugins
plugins:
  - search

# Markdown扩展
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde